# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_timestamp', models.DateTimeField(verbose_name='query time')),
                ('profanity_filter', models.NullBooleanField(default=False)),
                ('adult_filter', models.NullBooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeitgeist.SearchQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='search_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeitgeist.SearchResultSet'),
        ),
        migrations.AddField(
            model_name='parceltype',
            name='search_result_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeitgeist.SearchResultItem'),
        ),
        migrations.AddField(
            model_name='filter',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zeitgeist.SearchQuery'),
        ),
    ]
