# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitgeist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceltype',
            name='parcel_type',
            field=models.CharField(default='phrase', max_length=100),
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='item_text',
            field=models.CharField(default='<empty>', max_length=140),
        ),
    ]
