# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitgeist', '0002_auto_20170510_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='word',
            field=models.CharField(default='<empty>', max_length=140),
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
