# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitgeist', '0004_auto_20170511_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
