# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeitgeist', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_name',
            field=models.CharField(default='<empty>', max_length=140),
        ),
    ]
